// Code generated by MockGen. DO NOT EDIT.
// Source: services/integration/fixationservice/internal/usecase/deps.go
//
// Generated by this command:
//
//	mockgen -source=services/integration/fixationservice/internal/usecase/deps.go -destination=services/integration/fixationservice/internal/usecase/mocks/usecase_mocks.go -package=usecasemocks
//

// Package usecasemocks is a generated GoMock package.
package usecasemocks

import (
	entity "Broker_backend/services/integration/fixationservice/internal/domain/entity"
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFixationRepository is a mock of FixationRepository interface.
type MockFixationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFixationRepositoryMockRecorder
	isgomock struct{}
}

// MockFixationRepositoryMockRecorder is the mock recorder for MockFixationRepository.
type MockFixationRepositoryMockRecorder struct {
	mock *MockFixationRepository
}

// NewMockFixationRepository creates a new mock instance.
func NewMockFixationRepository(ctrl *gomock.Controller) *MockFixationRepository {
	mock := &MockFixationRepository{ctrl: ctrl}
	mock.recorder = &MockFixationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixationRepository) EXPECT() *MockFixationRepositoryMockRecorder {
	return m.recorder
}

// FixationCurrent mocks base method.
func (m *MockFixationRepository) FixationCurrent(ctx context.Context, phoneHash string, projectID uuid.UUID) (*entity.Fixation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FixationCurrent", ctx, phoneHash, projectID)
	ret0, _ := ret[0].(*entity.Fixation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FixationCurrent indicates an expected call of FixationCurrent.
func (mr *MockFixationRepositoryMockRecorder) FixationCurrent(ctx, phoneHash, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FixationCurrent", reflect.TypeOf((*MockFixationRepository)(nil).FixationCurrent), ctx, phoneHash, projectID)
}

// InsertAudit mocks base method.
func (m *MockFixationRepository) InsertAudit(ctx context.Context, f entity.Fixation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAudit", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAudit indicates an expected call of InsertAudit.
func (mr *MockFixationRepositoryMockRecorder) InsertAudit(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAudit", reflect.TypeOf((*MockFixationRepository)(nil).InsertAudit), ctx, f)
}

// InsertNewFixation mocks base method.
func (m *MockFixationRepository) InsertNewFixation(ctx context.Context, f entity.Fixation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertNewFixation", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertNewFixation indicates an expected call of InsertNewFixation.
func (mr *MockFixationRepositoryMockRecorder) InsertNewFixation(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertNewFixation", reflect.TypeOf((*MockFixationRepository)(nil).InsertNewFixation), ctx, f)
}

// InsertOutbox mocks base method.
func (m *MockFixationRepository) InsertOutbox(ctx context.Context, f entity.Fixation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOutbox", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOutbox indicates an expected call of InsertOutbox.
func (mr *MockFixationRepositoryMockRecorder) InsertOutbox(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOutbox", reflect.TypeOf((*MockFixationRepository)(nil).InsertOutbox), ctx, f)
}

// IsExistsProjectID mocks base method.
func (m *MockFixationRepository) IsExistsProjectID(ctx context.Context, projectID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExistsProjectID", ctx, projectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExistsProjectID indicates an expected call of IsExistsProjectID.
func (mr *MockFixationRepositoryMockRecorder) IsExistsProjectID(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExistsProjectID", reflect.TypeOf((*MockFixationRepository)(nil).IsExistsProjectID), ctx, projectID)
}

// IsUserIDInAgencyID mocks base method.
func (m *MockFixationRepository) IsUserIDInAgencyID(ctx context.Context, agencyID, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserIDInAgencyID", ctx, agencyID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserIDInAgencyID indicates an expected call of IsUserIDInAgencyID.
func (mr *MockFixationRepositoryMockRecorder) IsUserIDInAgencyID(ctx, agencyID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserIDInAgencyID", reflect.TypeOf((*MockFixationRepository)(nil).IsUserIDInAgencyID), ctx, agencyID, userID)
}

// UpdateFixationStatusExpired mocks base method.
func (m *MockFixationRepository) UpdateFixationStatusExpired(ctx context.Context, statusExpired entity.Status, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFixationStatusExpired", ctx, statusExpired, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFixationStatusExpired indicates an expected call of UpdateFixationStatusExpired.
func (mr *MockFixationRepositoryMockRecorder) UpdateFixationStatusExpired(ctx, statusExpired, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFixationStatusExpired", reflect.TypeOf((*MockFixationRepository)(nil).UpdateFixationStatusExpired), ctx, statusExpired, id)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockTxManager) Do(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Do indicates an expected call of Do.
func (mr *MockTxManagerMockRecorder) Do(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockTxManager)(nil).Do), ctx, fn)
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
}
