syntax = "proto3";

package broker.v1;

import "google/protobuf/timestamp.proto";

service BrokerService{
  rpc NewFixationCustomer(NewFixationCustomerRequest) returns (NewFixationCustomerResponse);
}

message NewFixationCustomerRequest{
  string broker_id = 1;
  string customer_id = 2;
  string fix_for = 3;
  string fixed_by = 4;
}

message NewFixationCustomerResponse{
  string fixation_id = 1;
  FixationStatus status = 2; //немного не понял зачем сделали отдельно тип и нигде не навесили конкретное значение из него
  google.protobuf.Timestamp fixed_at = 3;
  google.protobuf.Timestamp expires_at = 4;
}

enum FixationStatus{
  FIXATION_STATUS_ACTIVE = 0;
  FIXATION_STATUS_UNSPECIFIED = 1;
  FIXATION_STATUS_CONVERTED = 2;
  FIXATION_STATUS_EXPIRED = 3;
  FIXATION_STATUS_REMOVED = 4;
}