server:
  host: 0.0.0.0
  port: 50051

business:
  context_timeout: 5s

database:
  postgres:
    dsn: ""
    host: localhost
    port: 5432
    database_name: auth_pg
    username: postgres
    password: 2409
    ssl_mode: disable
    migrations_path: services/authservice/migrations
    migrations_table: goose_db_version
    schema_name: public
    max_connections: 10
    min_connections: 1
    max_idle_time: 30m
    max_lifetime: 60m
    health_check_period: 5m
    write_timeout: 30s
    read_timeout: 15s
    connect_timeout: 5s