// Code generated by MockGen. DO NOT EDIT.
// Source: services/integration/partnerapi/internal/transport/handlers/fixationhandlers/handler.go
//
// Generated by this command:
//
//	mockgen -source=services/integration/partnerapi/internal/transport/handlers/fixationhandlers/handler.go -destination=services/integration/partnerapi/internal/transport/handlers/fixationhandlers/mocks/fixation_client_mock.go -package=fixationhandlersmocks
//

// Package fixationhandlersmocks is a generated GoMock package.
package fixationhandlersmocks

import (
	v1 "Broker_backend/gen/fixation/v1"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFixationClient is a mock of FixationClient interface.
type MockFixationClient struct {
	ctrl     *gomock.Controller
	recorder *MockFixationClientMockRecorder
	isgomock struct{}
}

// MockFixationClientMockRecorder is the mock recorder for MockFixationClient.
type MockFixationClientMockRecorder struct {
	mock *MockFixationClient
}

// NewMockFixationClient creates a new mock instance.
func NewMockFixationClient(ctrl *gomock.Controller) *MockFixationClient {
	mock := &MockFixationClient{ctrl: ctrl}
	mock.recorder = &MockFixationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFixationClient) EXPECT() *MockFixationClientMockRecorder {
	return m.recorder
}

// NewFixation mocks base method.
func (m *MockFixationClient) NewFixation(ctx context.Context, req *v1.NewFixationRequest) (*v1.NewFixationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFixation", ctx, req)
	ret0, _ := ret[0].(*v1.NewFixationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewFixation indicates an expected call of NewFixation.
func (mr *MockFixationClientMockRecorder) NewFixation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFixation", reflect.TypeOf((*MockFixationClient)(nil).NewFixation), ctx, req)
}
